# -*- coding: utf-8 -*-
"""CodeGen_Stage3_LoRA_FineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNdfOaY_aJE-vrdCocQvWZLfmgotIqRk
"""

# 1. Verify the T4 GPU allocation
!nvidia-smi

# 2. Install the necessary PEFT and optimization libraries
!pip install -q transformers datasets peft bitsandbytes accelerate

import json
from datasets import Dataset
from transformers import AutoTokenizer

# 1. Initialize Tokenizer
MODEL_ID = "Salesforce/codegen-350M-mono"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

# 2. Open and Flatten Data Safely
with open("train_spider.json", "r", encoding="utf-8") as f:
    spider_train = json.load(f)

# Loop over the raw data and pull out ONLY the flat text fields we need.
# This strips away the nested SQL dictionaries that confuse PyArrow.
flattened_data = []
for entry in spider_train:
    flattened_data.append({
        "question": entry.get("question", ""),
        "db_id": entry.get("db_id", ""),
        "query": entry.get("query", "")  # Holds the golden target SQL string
    })

def formatting_prompts_func(examples):
    texts = []
    for q, db, target in zip(examples['question'], examples['db_id'], examples['query']):
        text = f"### Instruction:\nConvert this question to SQL for database: {db}\n### Question:\n{q}\n### Response:\n{target}<|endoftext|>"
        texts.append(text)
    return {"text": texts}

def tokenize_function(examples):
    model_inputs = tokenizer(examples["text"], truncation=True, max_length=512, padding=False)
    model_inputs["labels"] = model_inputs["input_ids"].copy()
    return model_inputs

# 3. Create Dataset from the clean, flattened list of pure strings
raw_dataset = Dataset.from_list(flattened_data)
text_dataset = raw_dataset.map(formatting_prompts_func, batched=True)
tokenized_dataset = text_dataset.map(tokenize_function, batched=True, remove_columns=text_dataset.column_names)

print("\n" + "="*50)
print(f"📊 Total records compiled for fine-tuning matrices: {len(tokenized_dataset)}")
print("="*50)

!pip install --upgrade torchao

"""Let's execute Step 4: Initializing the Model and Injecting LoRA Weights.

In this step, we will load the base CodeGen-350M weights in 16-bit precision to save VRAM, and then inject Low-Rank Adaptation (LoRA) matrices specifically targeting the Multi-Head Attention layer query and value projection gates (q_proj and v_proj).

Create a new code cell right below your data compilation cell, paste this block, and run it:
"""

import torch
from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, TaskType

print("⚙️ Loading foundational CodeGen weights...")

# 1. Load the base model in FP16
model = AutoModelForCausalLM.from_pretrained(
    "Salesforce/codegen-350M-mono",
    torch_dtype=torch.float16,
    device_map="auto"
)

# 2. Configure the LoRA Bottleneck targeting CodeGen's specific QKV projection
peft_config = LoraConfig(
    r=16, # have tried r=8, got exact match accuracy 12 %, trying 16 now.
    lora_alpha=32,
    target_modules=["qkv_proj"], # Updated for CodeGen architecture
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

# 3. Wrap the base model with the LoRA layers
model = get_peft_model(model, peft_config)

print("\n" + "="*50)
print("✅ LoRA Matrix Layer Injection Complete!")
model.print_trainable_parameters()
print("="*50)

from transformers import TrainingArguments, Trainer, DataCollatorForSeq2Seq

print("🏋️‍♂️ Setting up training configurations...")

# 1. Define Training Arguments
training_args = TrainingArguments(
    output_dir="./results/codegen_lora_sql",
    per_device_train_batch_size=4,   # Actual memory batch slice size
    gradient_accumulation_steps=4,   # Steps before updating weights (Effective Batch Size = 16)
    learning_rate=2e-4,              # Standard optimized LoRA learning rate
    logging_steps=10,                # Console feedback frequency
    num_train_epochs=5,              # 3 full iterations through your 7,000 samples
    save_strategy="epoch",           # Save model progress states after every epoch
    eval_strategy="no",              # Fix: removed the old 'evaluation_strategy' keyword completely
    fp16=True,                       # Use mixed-precision acceleration
    warmup_ratio=0.03,               # Slowly scale up the learning rate at start
    weight_decay=0.01,               # Pervasive regularization to prevent overfitting
    report_to="none"                 # Keeps execution independent of WandB or external hubs
)

# 2. Set up the dynamic padding collator
data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    pad_to_multiple_of=8,
    return_tensors="pt",
    padding=True
)

# 3. Instantiate the execution Trainer engine
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

print("🚀 Starting fine-tuning loop! Tracking loss optimization below...")
trainer.train()

# 1. Compress the entire results folder into a single zip archive
!zip -r codegen_lora_sql_checkpoints_r16.zip ./results/codegen_lora_sql

# 2. Use Colab's native utility to trigger an automatic browser download
from google.colab import files
files.download('codegen_lora_sql_checkpoints_r16.zip')

import torch
import json
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

MODEL_ID = "Salesforce/codegen-350M-mono"
CHECKPOINT_PATH = "./results/codegen_lora_sql/checkpoint-2190"

print("🔮 Initializing 5-sample verification pass...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto"
)
model = PeftModel.from_pretrained(base_model, CHECKPOINT_PATH)
model.eval()

# Load the validation data
try:
    with open("dev.json", "r", encoding="utf-8") as f:
        eval_data = json.load(f)
except FileNotFoundError:
    with open("train_spider.json", "r", encoding="utf-8") as f:
        eval_data = json.load(f)

print(f"✅ Data loaded successfully. Running execution on the first 5 samples:\n")

# Run exactly 5 loops
for i, entry in enumerate(eval_data[:5]):
    db = entry.get("db_id", "")
    question = entry.get("question", "")
    ground_truth = entry.get("query", "")

    prompt = f"### Instruction:\nConvert this question to SQL for database: {db}\n### Question:\n{question}\n### Response:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=64,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            num_beams=1,
            temperature=0.0
        )

    # Isolate the newly generated SQL string
    full_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_sql = full_output.split("### Response:\n")[-1].strip()

    print(f"--- [ Sample {i+1} ] ---")
    print(f"DB Context: {db}")
    print(f"Question:   {question}")
    print(f"Expected:   {ground_truth}")
    print(f"Model SQL:  {generated_sql}\n")

!unzip stage4_collab_transfer.zip -d ./

!python run_stage4_experiment.py