# -*- coding: utf-8 -*-
"""SingleCorpusDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzC-ZE1s2sdE5sqUB-ILNlZvDootkoIm
"""

# @title
# ============================================================
# INSTALL DEPENDENCIES
# ============================================================

!pip uninstall -y datasets huggingface_hub fsspec

!pip install -q \
datasets==2.19.2 \
huggingface_hub==0.23.5 \
fsspec==2024.3.1 \
pyarrow \
fastparquet \
pandas \
tqdm \
xxhash

print("Installation complete.")
print("Please restart the runtime before continuing.")

import datasets
import huggingface_hub
import fsspec

print("datasets:", datasets.__version__)
print("huggingface_hub:", huggingface_hub.__version__)
print("fsspec:", fsspec.__version__)


# ============================================================
# STEP 2: IMPORTS
# Run after runtime restart
# ============================================================

import os
import re
import logging
import pandas as pd
import xxhash

from tqdm.auto import tqdm
from datasets import load_dataset, Dataset

logging.basicConfig(
  level=logging.INFO,
  format="%(asctime)s - %(levelname)s - %(message)s"
)

print("Installation complete.")
print("Please Runtime -> Restart Session before continuing.")

# ============================================================
# CONFIG
# ============================================================

OUTPUT_DIR = "/content/unified_corpus"

MIN_CODE_LEN = 20
MAX_CODE_LEN = 500 #We can increase the count here, if we want more number of datasets.
MIN_DESC_LEN = 15

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# HELPERS
# ============================================================

def normalize_text(text):

  if text is None:
    return ""
  return str(text).strip()

def normalize_code(code):
  return re.sub(r"\s+", " ", str(code)).strip()

def code_hash(code):
  return xxhash.xxh64(
  normalize_code(code).encode("utf-8")).hexdigest()

def valid_record(code, desc):

  if not code:
    return False

  if not desc:
    return False

  if len(code) < MIN_CODE_LEN:
    return False

  if len(code) > MAX_CODE_LEN:
    return False

  if len(desc) < MIN_DESC_LEN:
    return False

  if len(desc.split()) < 3:
    return False

  return True

# ============================================================
# DATASET SIZE INSPECTION
# ============================================================

languages = [
"python",
"java"
#"javascript",
#"php",
#"ruby",
#"go"
]

print("=" * 80)
print("VERIFY CODESEARCHNET ACCESS")
print("=" * 80)

stats = []
total_rows = 0

for lang in languages:

  try:

    ds = load_dataset(
        "code_search_net",
        lang,
        split="train"
    )

    rows = len(ds)

    total_rows += rows

    print(
        f"{lang:<12} {rows:,}"
    )

    stats.append({
        "dataset": "CodeSearchNet",
        "language": lang,
        "rows": rows
    })

  except Exception as e:

    print(
        f"{lang:<12} FAILED"
    )

    print(e)

  stats_df = pd.DataFrame(stats)

  print("\nSummary")
  print(stats_df)

  print(
  f"\nTotal Rows: {total_rows:,}"
)

# ============================================================
# OPTIONAL:
# VERIFY CODEXGLUE CODE-TO-TEXT DATASET
# ============================================================

print("\n" + "=" * 80)
print("VERIFY CODEXGLUE")
print("=" * 80)

codexglue_langs = [
"python",
"java"
#"javascript",
#"php",
#"ruby",
#"go"
]

for lang in codexglue_langs:

  try:

    ds = load_dataset(
        "code_x_glue_ct_code_to_text",
        lang,
        split="train"
    )

    print(
        f"{lang:<12} {len(ds):,}"
    )

  except Exception as e:

    print(
        f"{lang:<12} FAILED"
    )

    print(e)

# ============================================================
# LOAD CODESEARCHNET
# ============================================================

records = []

print("\n" + "=" * 80)
print("LOADING CODESEARCHNET")
print("=" * 80)

for lang in languages:

  try:

    ds = load_dataset(
        "code_search_net",
        lang,
        split="train"
    )

    print(
        f"\nLoading {lang}"
    )

    print(
        "Columns:",
        ds.column_names
    )

    for row in tqdm(
        ds,
        desc=f"CSN-{lang}"
    ):

        code = normalize_text(
            row.get(
                "whole_func_string"
            )
        )

        desc = normalize_text(
            row.get(
                "func_documentation_string"
            )
        )

        if not valid_record(
            code,
            desc
        ):
            continue

        records.append({
            "language": lang,
            "code": code,
            "description": desc,
            "source": "codesearchnet"
        })

  except Exception as e:

    print(
        f"Failed loading {lang}"
    )

    print(e)

print(
f"\nCodeSearchNet records collected: {len(records):,}"
)

# ============================================================
# LOAD CODEXGLUE
# ============================================================

print("\n" + "=" * 80)
print("LOADING CODEXGLUE")
print("=" * 80)

for lang in codexglue_langs:

  try:

    ds = load_dataset(
        "code_x_glue_ct_code_to_text",
        lang,
        split="train"
    )

    before = len(records)

    for row in tqdm(
        ds,
        desc=f"CodeXGLUE-{lang}"
    ):

        code = normalize_text(
            row.get("code")
        )

        desc = normalize_text(
            row.get("docstring")
        )

        if not valid_record(
            code,
            desc
        ):
            continue

        records.append({
            "language": lang,
            "code": code,
            "description": desc,
            "source": "codexglue"
        })

    print(
        f"{lang}: added {len(records)-before:,}"
    )

  except Exception as e:

    print(
        f"CodeXGLUE {lang} failed"
    )

    print(e)

# ============================================================
# SAFETY CHECK
# ============================================================

if len(records) == 0:

  raise RuntimeError(
    "No records loaded. Verify dataset access."
)

print(f"total number pf records: ", len(records));

# ============================================================

# DATAFRAME

# ============================================================

df = pd.DataFrame(records)

if df.empty:

  raise RuntimeError(
    "DataFrame is empty."
)

print(
f"\nRows before dedup: {len(df):,}"
)

# ============================================================
# DEDUPLICATION
# ============================================================

df["hash"] = df["code"].apply(
code_hash
)

before = len(df)

df = (
df
.drop_duplicates(
subset=["hash"]
)
.drop(
columns=["hash"]
)
.reset_index(drop=True)
)

print(
f"Duplicates removed: {before-len(df):,}"
)

print(
f"Rows after dedup: {len(df):,}"
)

# ============================================================
# SHUFFLE
# ============================================================

df = df.sample(
frac=1,
random_state=42
).reset_index(drop=True)

# ============================================================

# STATS

# ============================================================

print("\nSource Distribution")
print(
df["source"].value_counts()
)

print("\nLanguage Distribution")
print(
df["language"].value_counts()
)

# ============================================================

# SAVE PARQUET

# ============================================================

PARQUET_FILE = (
f"{OUTPUT_DIR}/unified_corpus.parquet"
)

df.to_parquet(
PARQUET_FILE,
index=False
)

print(
f"\nSaved parquet: {PARQUET_FILE}"
)

# ============================================================

# HF DATASET

# ============================================================

hf_ds = Dataset.from_pandas(
df,
preserve_index=False
)

split_1 = hf_ds.train_test_split(
test_size=0.10,
seed=42
)

train_ds = split_1["train"]
temp_ds = split_1["test"]

split_2 = temp_ds.train_test_split(
test_size=0.50,
seed=42
)

valid_ds = split_2["train"]
test_ds = split_2["test"]

print("\nDataset Sizes")

print(
"Train:",
len(train_ds)
)

print(
"Validation:",
len(valid_ds)
)

print(
"Test:",
len(test_ds)
)

train_ds.save_to_disk(
f"{OUTPUT_DIR}/train"
)

valid_ds.save_to_disk(
f"{OUTPUT_DIR}/validation"
)

test_ds.save_to_disk(
f"{OUTPUT_DIR}/test"
)

print("\nCompleted Successfully")

print("\nExample Record")
print(train_ds[0])