# src/processor.py
import re

def clean_generated_sql(raw_text):
    """
    Takes raw text generated by the model after the 'Analysis:' prompt trigger,
    parses the multi-task 'Corrected_SQL:' field, and returns a clean, executable SQL statement.
    """
    # 1. Structural multi-task anchoring and splitting
    if "Corrected_SQL:" in raw_text:
        raw_text = raw_text.split("Corrected_SQL:")[-1]
    elif "|" in raw_text:
        # Fallback safety guard if the model omits the exact keyword but keeps the pipe
        raw_text = raw_text.split("|")[-1]

    lines = raw_text.split("\n")
    valid_sql_lines = []
    
    for line in lines:
        stripped = line.strip()
        
        # Halt processing if the model leaks template tags, structural markers, or repeating loops
        if (stripped.startswith("```") or 
            stripped.startswith("#") or 
            stripped.startswith("###") or
            stripped.startswith("[Task:") or
            "Question:" in line or
            "Schema:" in line or
            "Analysis:" in line):
            break
            
        valid_sql_lines.append(line)
        
    generated_sql_clean = " ".join(valid_sql_lines).strip()
    
    # Strip out leftover markdown syntax identifiers if present
    generated_sql_clean = re.sub(r"^sql\s*", "", generated_sql_clean, flags=re.IGNORECASE)
    
    # Normalize dense whitespace tokens caused by line aggregation loops
    final_sql = " ".join(generated_sql_clean.split()).strip()
    
    # Strip trailing semicolon for execution engine metric consistency
    if final_sql.endswith(";"):
        final_sql = final_sql[:-1].strip()
        
    return final_sql

    
def clean_generated_nosql(raw_text):
    """
    Takes raw text generated by the model after the 'Analysis:' prompt trigger,
    parses the multi-task 'Final_MQL:' field, and isolates the executable MongoDB query.
    """
    # 1. Structural multi-task anchoring and splitting
    if "Final_MQL:" in raw_text:
        raw_text = raw_text.split("Final_MQL:")[-1]
    elif "|" in raw_text:
        # Fallback safety guard if the model omits the exact keyword but keeps the pipe
        raw_text = raw_text.split("|")[-1]

    lines = raw_text.split("\n")
    valid_nosql_lines = []
    
    for line in lines:
        stripped = line.strip()
        
        # Halt processing if the model leaks template tags or structural markers
        if (stripped.startswith("```") or 
            stripped.startswith("#") or 
            stripped.startswith("###") or
            stripped.startswith("[Task:") or
            "SQL:" in line or
            "Input SQL:" in line or
            "Schema:" in line or
            "Analysis:" in line):
            break
            
        valid_nosql_lines.append(line)
        
    generated_nosql_clean = " ".join(valid_nosql_lines).strip()
    
    # Strip out leftover markdown execution engine tags if present
    generated_nosql_clean = re.sub(r"^(javascript|json|mql)\s*", "", generated_nosql_clean, flags=re.IGNORECASE)
    
    # Clean up double spacing caused by multi-line squashing
    final_mql = " ".join(generated_nosql_clean.split()).strip()
    
    return final_mql